[tool.black]
line-length = 120
skip-string-normalization = true

[tool.mypy]
check_untyped_defs = true
warn_redundant_casts = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
no_implicit_optional = true
no_implicit_reexport = true
